Add Dawn to apps
mastodon/joinmastodon pull request #332
Opened 2023-03-26 18:11 UTC by noppefoxwolf

Nightfox dawn is new iOS app for mastodon.
https://apps.apple.com/app/nightfox-dawn/id1668645019

2023-07-10 00:38 UTC, noppefoxwolf commented
@renchap I have resolved conflicts at times. Can you merge this Pull Request?

2023-07-11 21:38 UTC, andypiper commented
Hi, is this app available globally? I am not seeing it in the App Store (UK)

2023-07-12 05:46 UTC, noppefoxwolf commented
Now, it's released in the US, JP, and a few other countries. Do I have to release globally to merge this PR?

2023-07-12 15:41 UTC, andypiper commented
It does mean that I'm not able to try it myself 😄 I think it would be preferable to list apps that are available anywhere, otherwise people may be confused if they click on a link that appears to be broken.

2023-07-13 10:24 UTC, andypiper commented
I've updating the Contributing.md file now to say that we prefer apps that are globally-available. If you choose to distribute more widely in the future, happy to look back at this PR. Thank you!

2023-07-13 12:31 UTC, noppefoxwolf commented
Thank you for updating Contribute guideline.
I'll challenge to localize/release globally-available.

2023-10-23 03:21 UTC, noppefoxwolf commented
@andypiper DAWN is now on available in global. I reopened this PR. Will you review again for me?

2023-10-23 10:00 UTC, andypiper requested changes

2023-10-23 10:00 UTC, andypiper commented on data/apps.ts
> +      name: "Nightfox DAWN",
In the iOS App Store this is called "DAWN for Mastodon", please update this here to that it matches. Thanks!

2023-11-13 14:51 UTC, andypiper approved these changes

2023-11-13 14:51 UTC, merged